### ISSUE TITLE
Program wont start properly

### ISSUE THREAD

**Issue by Lebberworscht** [anooplab/pyar#4]
Hi,
i try to use the aggregation function of pyar but the programm will always top after "starting aggregation in {starting_directory}.
Do you know how the solve this problem?

Starting PyAR at 22 Jul 2020, 20:32:58
Job directory: /scratch/x/pyartest
Parsing the following files: 
 A.xyz 0 1 rhf
QM Software:   xtb
Number of orientations: 4
Maximum number of seeds: 8
Starting Aggregation in
 {starting_directory}

**Comment by anooplab** [comment]
Can you show the command line argument that you have used? 
Was there any error in the terminal?

**Comment by Lebberworscht** [comment]
pyar-cli -a A.xyz -N 4 -as 20 --software xtb

There were no errors in the terminal.

**Comment by anooplab** [comment]
Please upgrade to the new version.  The aggregate_size of 20 was too much.  Now it should be fine. Please try.
