### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by manassharma07** [anooplab/pyar#5]
I am interested in performing global optimization using PyAR but unfortunately I am having a hard time getting started because I can't find any documentation or tutorial.

Is there some webpage that you could guide me to?

**Comment by anooplab** [comment]
Documentation is long due. If the installation is done properly, the help on the command line interface is available by 
`pyar-cli -h`

Some examples of this is given in the README.md

### Reaction

To study the reaction between two reactants A and B using ORCA software interface, with force from 100 to 1000 using N=8 trial orientation, the commandline line argument is,

`pyar-cli -r A.xyz B.xyz -N 8 -gmin 100 -gmax 1000 --ssoftware orca
`
A.xyz and B.xyz are the cartesian coordinate files of the reactants.

### Aggregation and clustering
`
pyar-cli -a A.xyz -N 8 -as 10 --software xtb`

This will generate a molecular aggregate/cluster of size upto 10 with XTB package using 8 trial orientations. The A.xyz is a standard cartesian coordinate file. For example the .xyz file for a carbon atom is the following:

```
1
Comment
C  0.0  0.0   0.0
```

**Comment by manassharma07** [comment]
Thanks for the prompt response. The installations was successful and I was using the -h option.

But I still have a few doubts.

For example if I want to get the global minimum structure of Zn6O6 nanocluster, then should I use the following?

`pyar-cli -a ZnO.xyz -N 8 -as 6 --software turbomole`

where `ZnO.xyz` is:

```
2
Comment
Zn  0.0  0.0   0.0
O   1.2  0.0   0.0
```

I also didn't quite understand what is 'N' (Number of orientations) supposed to mean here. What should I use for N to be able to find the optimum nanocluster geometry?

**Comment by anooplab** [comment]
Yes, the command is correct. 
N is the number of trial orientations used in each cluster_size cycles. 
For example, initially one molecule of ZnO is added to another ZnO. N randomly generated relative orientation will be optimized.
