### ISSUE TITLE
Please add the list of dependencies required in the README

### ISSUE THREAD

**Issue by manassharma07** [anooplab/pyar#6]
It seems like one requires libraries like pandas, sklearn, etc to run PyAR.

A suggestion would be to add a `requirements.txt` as well as in the README a list of libraries required.

`requirements.txt` allows to automatically install the dependencies.

I also noticed that f-strings are used in the code which are supported for Python 3.6 or higher. So it may also be useful to add that to the readme.

**Comment by anooplab** [comment]
Thanks a lot. Added requirements to the file and to README. 
Docstring based doc by Sphinx is also added (not so clean). 

Best regards, 

[ http://chemistry.iitkgp.ac.in/~anoop | anoop ]
