### ISSUE TITLE
Convergence failure for orientation number>8

### ISSUE THREAD

**Issue by akhilsnair2017** [anooplab/pyar#7]
When I try to do aggregation  for orientation number >8, error pops up '**/apps/compiler/anaconda/python/3.7/lib/python3.7/site-packages/sklearn/cluster/k_means_.py:971: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (8). Possibly due to duplicate points in X**.'
and aggregation stops for dimer with no geometries in the 'selected' directory.
Running command used: pyar-cli -N 16 -s seed.xyz monomer.xyz -ss 19 --software xtb -v 0 > run.log

The error corresponding portion of k_means_.py is:
`        self.cluster_centers_, self.labels_, self.inertia_, self.n_iter_ = \
            k_means(
                X, n_clusters=self.n_clusters, sample_weight=sample_weight,
                init=self.init, n_init=self.n_init,
                max_iter=self.max_iter, verbose=self.verbose,
                precompute_distances=self.precompute_distances,
                tol=self.tol, random_state=random_state, copy_x=self.copy_x,
                n_jobs=self.n_jobs, algorithm=self.algorithm,
                return_n_iter=True)`

May I know what could be the solution?

**Comment by anooplab** [comment]
This happens because all the optimized geometries after the first cycle are the same (very similar). Therefore kmeans fails in clustering.  I have committed a quick fix. You may upgrade and try.
